# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: borrowing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'borrowing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62orrowing.proto\x12\tborrowing\"5\n\x11\x42orrowGameRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07game_id\x18\x02 \x01(\x03\")\n\x11ReturnGameRequest\x12\x14\n\x0c\x62orrowing_id\x18\x01 \x01(\x03\"-\n\x1aGetBorrowingHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"+\n\x13GetBorrowingRequest\x12\x14\n\x0c\x62orrowing_id\x18\x01 \x01(\x03\"\x97\x01\n\x11\x42orrowingResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0f\n\x07game_id\x18\x03 \x01(\x03\x12\x13\n\x0b\x62orrowed_at\x18\x04 \x01(\t\x12\x13\n\x0breturned_at\x18\x05 \x01(\t\x12*\n\x06status\x18\x06 \x01(\x0e\x32\x1a.borrowing.BorrowingStatus\"L\n\x18\x42orrowingHistoryResponse\x12\x30\n\nborrowings\x18\x01 \x03(\x0b\x32\x1c.borrowing.BorrowingResponse*q\n\x0f\x42orrowingStatus\x12 \n\x1c\x42ORROWING_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x42ORROWING_STATUS_BORROWED\x10\x01\x12\x1d\n\x19\x42ORROWING_STATUS_RETURNED\x10\x02\x32\xd7\x02\n\x10\x42orrowingService\x12H\n\nBorrowGame\x12\x1c.borrowing.BorrowGameRequest\x1a\x1c.borrowing.BorrowingResponse\x12H\n\nReturnGame\x12\x1c.borrowing.ReturnGameRequest\x1a\x1c.borrowing.BorrowingResponse\x12\x61\n\x13GetBorrowingHistory\x12%.borrowing.GetBorrowingHistoryRequest\x1a#.borrowing.BorrowingHistoryResponse\x12L\n\x0cGetBorrowing\x12\x1e.borrowing.GetBorrowingRequest\x1a\x1c.borrowing.BorrowingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'borrowing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BORROWINGSTATUS']._serialized_start=452
  _globals['_BORROWINGSTATUS']._serialized_end=565
  _globals['_BORROWGAMEREQUEST']._serialized_start=30
  _globals['_BORROWGAMEREQUEST']._serialized_end=83
  _globals['_RETURNGAMEREQUEST']._serialized_start=85
  _globals['_RETURNGAMEREQUEST']._serialized_end=126
  _globals['_GETBORROWINGHISTORYREQUEST']._serialized_start=128
  _globals['_GETBORROWINGHISTORYREQUEST']._serialized_end=173
  _globals['_GETBORROWINGREQUEST']._serialized_start=175
  _globals['_GETBORROWINGREQUEST']._serialized_end=218
  _globals['_BORROWINGRESPONSE']._serialized_start=221
  _globals['_BORROWINGRESPONSE']._serialized_end=372
  _globals['_BORROWINGHISTORYRESPONSE']._serialized_start=374
  _globals['_BORROWINGHISTORYRESPONSE']._serialized_end=450
  _globals['_BORROWINGSERVICE']._serialized_start=568
  _globals['_BORROWINGSERVICE']._serialized_end=911
# @@protoc_insertion_point(module_scope)
