# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import borrowing_pb2 as borrowing__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in borrowing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BorrowingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BorrowGame = channel.unary_unary(
                '/borrowing.BorrowingService/BorrowGame',
                request_serializer=borrowing__pb2.BorrowGameRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowingResponse.FromString,
                _registered_method=True)
        self.ReturnGame = channel.unary_unary(
                '/borrowing.BorrowingService/ReturnGame',
                request_serializer=borrowing__pb2.ReturnGameRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowingResponse.FromString,
                _registered_method=True)
        self.GetBorrowingHistory = channel.unary_unary(
                '/borrowing.BorrowingService/GetBorrowingHistory',
                request_serializer=borrowing__pb2.GetBorrowingHistoryRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowingHistoryResponse.FromString,
                _registered_method=True)
        self.GetBorrowing = channel.unary_unary(
                '/borrowing.BorrowingService/GetBorrowing',
                request_serializer=borrowing__pb2.GetBorrowingRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowingResponse.FromString,
                _registered_method=True)


class BorrowingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def BorrowGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBorrowingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBorrowing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BorrowingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BorrowGame': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowGame,
                    request_deserializer=borrowing__pb2.BorrowGameRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowingResponse.SerializeToString,
            ),
            'ReturnGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnGame,
                    request_deserializer=borrowing__pb2.ReturnGameRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowingResponse.SerializeToString,
            ),
            'GetBorrowingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowingHistory,
                    request_deserializer=borrowing__pb2.GetBorrowingHistoryRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowingHistoryResponse.SerializeToString,
            ),
            'GetBorrowing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowing,
                    request_deserializer=borrowing__pb2.GetBorrowingRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'borrowing.BorrowingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('borrowing.BorrowingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BorrowingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BorrowGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/BorrowGame',
            borrowing__pb2.BorrowGameRequest.SerializeToString,
            borrowing__pb2.BorrowingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/ReturnGame',
            borrowing__pb2.ReturnGameRequest.SerializeToString,
            borrowing__pb2.BorrowingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBorrowingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/GetBorrowingHistory',
            borrowing__pb2.GetBorrowingHistoryRequest.SerializeToString,
            borrowing__pb2.BorrowingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBorrowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/GetBorrowing',
            borrowing__pb2.GetBorrowingRequest.SerializeToString,
            borrowing__pb2.BorrowingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
