name: Game Catalog Service

on:
  push:
    branches:
        - main
    pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: game_catalog
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d game_catalog"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    defaults:
      run:
        working-directory: game-catalog-service

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests
        run: ./mvnw test
        env:
          SPRING_R2DBC_URL: r2dbc:postgresql://localhost:5432/game_catalog
          SPRING_R2DBC_USERNAME: postgres
          SPRING_R2DBC_PASSWORD: postgres

  docker:
    needs: test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./game-catalog-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/board-game-catalog-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/board-game-catalog-service:${{ github.sha }}